-keepnames class pl.selvin.android.listsyncsample.ui.** extends androidx.fragment.app.Fragment
-keep class pl.selvin.android.listsyncsample.ui.** extends pl.selvin.android.listsyncsample.app.ListFragmentCommon
-dontwarn okio.**
-dontnote okhttp3.**
-dontnote android.net.**
-dontnote org.apache.**
-dontnote pl.selvin.android.syncframework.content.**
-keep class net.sqlcipher.** { *; }
-keep public class net.sqlcipher.database.** { *; }