name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/checkout@v3
        with:
          repository: selvinpl/maven
          persist-credentials: false
          path: build/maven


      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishReleasePublicationToMavenRepository
        env:
          GITHUB_RELEASE: ${{ github.event.release.tag_name }}

      - name: Pushes to another repository
        run: |
          cd build/maven
          git config --global user.name '${{ secrets.USER }}' 
          git config --global user.email '${{ secrets.EMAIL }}'
          git add --all
          git remote set-url origin https://${{ secrets.USER }}:${{ secrets.ACCESS_TOKEN }}@github.com/SelvinPL/maven.git
          git commit -m '[automated commit]'
          git push

 #   - name: Publish to GitHub Packages
 #     uses: gradle/gradle-build-action@v2
 #     with:
 #       arguments: publish
 #     env:
 #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 #       GITHUB_RELEASE: ${{ github.event.release.tag_name }}
